# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhaIka4z_Kbf2QSxY_FXf3XO0PXxTAwV
"""
#Robin Stumpp Melquiot Theophile 
from pyspark import SparkContext
sc = SparkContext()
lines = sc.textFile("sample.txt")
word_count = lines. flatMap(lambda line: line.split(' ')) \
 .map(lambda word: (word, 1)) \
 .reduceByKey(lambda count1, count2: count1 + count2) \
 .persist()

for (word, count) in word_count.collect():
  print(word, count)
input("Press ctrl+c to exit")

from pyspark import SparkContext
sc = SparkContext()
lines = sc.textFile("sample.txt")
word_count = lines. flatMap(lambda line: line.split(' ')) \
 .map(lambda word: (word, 1)) \
 .reduceByKey(lambda count1, count2: count1 + count2) \
 .persist()

top_3_words = word_count.takeOrdered(3, key=lambda t: -t[1])
print("Top 3 most present words:")
for word, count in top_3_words:
    print(word, count)

num_unique_words = word_count.count()
print("Number of different words:", num_unique_words)

input("Press ctrl+c to exit")
#Robin Stumpp Melquiot Theophile 